mutation CreditFacilityProposalCollateralUpdate(
  $input: CreditFacilityProposalCollateralUpdateInput!
) {
  creditFacilityProposalCollateralUpdate(input: $input) {
    creditFacilityProposal {
      creditFacilityProposalId
    }
  }
}
