mutation CreditFacilityProposalCreate(
  $input: CreditFacilityProposalCreateInput!
) {
  creditFacilityProposalCreate(input: $input) {
    creditFacilityProposal {
      creditFacilityProposalId
    }
  }
}
