mutation ExecuteManualTransaction($input: ManualTransactionExecuteInput!) {
  manualTransactionExecute(input: $input) {
    transaction {
      ledgerTransactionId
      createdAt
      effective
      description
      entries {
        entryId
        txId
      }
    }
  }
}
