mutation PendingCreditFacilityCollateralUpdate(
  $input: PendingCreditFacilityCollateralUpdateInput!
) {
  pendingCreditFacilityCollateralUpdate(input: $input) {
    pendingCreditFacility {
      pendingCreditFacilityId
    }
  }
}
